<?php
/**
 * grad.ucla functions and definitions
 *
 * @package grad.ucla
 */

/**
 * Set the content width based on the theme's design and stylesheet.
 */
if ( ! isset( $content_width ) ) {
	$content_width = 640; /* pixels */
}

if ( ! function_exists( 'grad_ucla_setup' ) ) :
/**
 * Sets up theme defaults and registers support for various WordPress features.
 *
 * Note that this function is hooked into the after_setup_theme hook, which
 * runs before the init hook. The init hook is too late for some features, such
 * as indicating support for post thumbnails.
 */
function grad_ucla_setup() {

	/*
	 * Make theme available for translation.
	 * Translations can be filed in the /languages/ directory.
	 * If you're building a theme based on grad.ucla, use a find and replace
	 * to change 'grad-ucla' to the name of your theme in all the template files
	 */
	load_theme_textdomain( 'grad-ucla', get_template_directory() . '/languages' );

	// Add default posts and comments RSS feed links to head.
	add_theme_support( 'automatic-feed-links' );

	/*
	 * Enable support for Post Thumbnails on posts and pages.
	 *
	 * @link http://codex.wordpress.org/Function_Reference/add_theme_support#Post_Thumbnails
	 */
	//add_theme_support( 'post-thumbnails' );

	// This theme uses wp_nav_menu() in one location.
	register_nav_menus( array(
		'primary' => __( 'Primary Menu', 'grad-ucla' ),
	) );
	
	/*
	 * Switch default core markup for search form, comment form, and comments
	 * to output valid HTML5.
	 */
	add_theme_support( 'html5', array(
		'search-form', 'comment-form', 'comment-list', 'gallery', 'caption'
	) );

	/*
	 * Enable support for Post Formats.
	 * See http://codex.wordpress.org/Post_Formats
	 */
	add_theme_support( 'post-formats', array(
		'aside', 'image', 'video', 'quote', 'link'
	) );

	// Setup the WordPress core custom background feature.
	add_theme_support( 'custom-background', apply_filters( 'grad_ucla_custom_background_args', array(
		'default-color' => 'ffffff',
		'default-image' => '',
	) ) );
	
	// add support for featured images on pages
	add_theme_support('post-thumbnails');
}
endif; // grad_ucla_setup
add_action( 'after_setup_theme', 'grad_ucla_setup' );

/**
 * Register widget area.
 *
 * @link http://codex.wordpress.org/Function_Reference/register_sidebar
 */
function grad_ucla_widgets_init() {
	register_sidebar( array(
		'name'          => __( 'Sidebar', 'grad-ucla' ),
		'id'            => 'sidebar-1',
		'description'   => '',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h1 class="widget-title">',
		'after_title'   => '</h1>',
	) );
}
add_action( 'widgets_init', 'grad_ucla_widgets_init' );

/**
 * Enqueue scripts and styles.
 */
function grad_ucla_scripts() {


//==================================================================================================
//  SCRIPTS
//==================================================================================================

	//the following two scripts can be useful for debugging, but shouldn't be registered or loaded in production
	//non-minified version of underscore.js
	wp_register_script('underscore-full', get_template_directory_uri() . '/js/lib/underscore.js', array('jquery'), '20140903', true );
	//non-minified version of backbone.js
	wp_register_script('backbone-full', get_template_directory_uri() . '/js/lib/backbone.js', array('jquery', 'underscore-full'), '20140903', true );
	
	//backbone-forms library to render and validate forms with backbone.js
	wp_register_script('backbone-forms', get_template_directory_uri() . '/js/lib/backbone-forms.js', array('backbone'), '20140904', true );

	//list.js is a plugin for backbone-forms which enables the "List" Editor type
	wp_register_script('backbone-forms-list', get_template_directory_uri() . '/js/lib/list.js', array('backbone', 'backbone-forms'), '20141003', true );

//==================================================================================================
//  STYLESHEETS
//==================================================================================================	
	
	//font awesome, used for icons
	wp_enqueue_style('font-awesome', '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css');
	
	//base style.css, mostly generated by underscores (_s) theme
	wp_enqueue_style( 'grad-ucla-style-base', get_stylesheet_uri() );
	
	//styles ported from pre-existing UCLA templates. specifically "ucla-gateway-1.3.0"
	wp_enqueue_style( 'grad-ucla-style-common', get_stylesheet_directory_uri(). '/css/ucla-common.css' );
	
	//general customizations loaded on top of previous styles (device agnostic)
	wp_enqueue_style( 'grad-ucla-style-custom', get_stylesheet_directory_uri(). '/css/custom.css' );
	
	//css @media queries to alter display for different device sizes
	wp_enqueue_style( 'grad-ucla-style-responsive', get_stylesheet_directory_uri(). '/css/responsive.css' );

	//jquery-based navigation, only used for <768px wide devices. toggles navigation menu and search bar display
	wp_enqueue_script( 'grad-ucla-navigation', get_template_directory_uri() . '/js/jquery-navigation.js', array('jquery'), '20140815', true );

	//included with underscores (_s) theme
	wp_enqueue_script( 'grad-ucla-skip-link-focus-fix', get_template_directory_uri() . '/js/skip-link-focus-fix.js', array(), '20130115', true );
	
	//parallax scrolling effect, mainly used on "hero" header image
	wp_enqueue_script( 'grad-ucla-parallax', get_template_directory_uri() . '/js/gd-parallax.js', array('jquery', 'underscore'), '20140826', true );
	
	//changes underscore.js template syntax to not possibly conflict with ASP-style tags. before: <% %>, after: <# #>
	wp_register_script('underscore-template-settings', get_template_directory_uri() . '/js/underscore-template-settings.js', array('underscore'), '20140820', true );

	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
}
add_action( 'wp_enqueue_scripts', 'grad_ucla_scripts' );

/**
 * Implement the Custom Header feature.
 */
//require get_template_directory() . '/inc/custom-header.php';

/**
 * Custom template tags for this theme.
 */
require get_template_directory() . '/inc/template-tags.php';

/**
 * Custom functions that act independently of the theme templates.
 */
require get_template_directory() . '/inc/extras.php';

/**
 * Customizer additions.
 */
require get_template_directory() . '/inc/customizer.php';

/**
 * Load Jetpack compatibility file.
 */
require get_template_directory() . '/inc/jetpack.php';

/**
 * Load our custom PHP functions
 */
require get_template_directory() . '/inc/custom-functions.php';